### PR TITLE
Add delete functionality

### LINKED ISSUE #1: I'm unable to delete my order
Title is pretty self-explanatory

### PR DESCRIPTION
**Pull request by seanbecker15**
* Add delete method to order controller
* Update tests to check that we can delete orders
* Fixes #1

### CODE REVIEW

**Comment by seanbecker15** [comment]
Fixes #1

**Comment by scottmangiapane** [comment]
LOL. This project is actually for a take-home interview, but I'd merge it if I could 😂

**Comment by scottmangiapane** [comment]
Maybe in a week

**Comment by seanbecker15** [comment]
Hahaha. Open source coordinator ✅  Senior Scott here we come 🚀

**Pull request closed without merging**
